### ISSUE TITLE
setBouncingOptions is not a function

### ISSUE THREAD

**Issue by LeChatNoir69** [hosuaby/Leaflet.SmoothMarkerBouncing#20]
Hi,

I try to use your plugin on my joomla website but I can't make it run.
Console display "setBouncingOptions is not a function"...

Here it is : https://climbingaway.fr/maquette/fr/sites-escalade/les-20-sites-autour-de-chez-toi

Could you see something wrong ? I can't fid the issue. The leaflet.smoothmarkerbouncing.js script is loaded (in a script merge by Joomla) but it seems that the leaflet class is not surcharge by your plugin..

**Comment by hosuaby** [comment]
Hello, @LeChatNoir69 

Sorry for a late response. I think this issue is no longer relevant so I will close it.

Concerning that problem. Probably plugin was not properly imported. Need to see how was it added to the page and what are the other imported scripts.

If it still relevant, you can post your code here so I can help to understand.
