### ISSUE TITLE
Property style on undefined.

### ISSUE THREAD

**Issue by dbielak** [hosuaby/Leaflet.SmoothMarkerBouncing#21]
Hi, i have a problem with marker when is starting bouncing. It's make an error loop with message 
```
"Uncaught TypeError: Cannot read property 'style' of undefined
    at makeMoveStep (leaflet.smoothmarkerbouncing.js:659)"
```
I have a custom Icon somthing like that
```
const ICON = L.icon( {
  iconUrl: require('./icons/javascript.png'),
  iconSize:     [44, 44], 
  iconAnchor:   [22, 44], 
  popupAnchor:  [-3, -44]
})
```

Do you know what is a problem?

**Comment by MACscr** [comment]
Get this resolved? Im having the same issue.

**Comment by ankit22687** [comment]
I found solution by addding if condition before  line no. 659

I added this condition at couple of places, so the condition is 

if(icon){
// code 
}

**Comment by tomek-servlets** [comment]
Unfortunately, the problem still exists.

**Comment by hosuaby** [comment]
This issue was solved in https://github.com/hosuaby/Leaflet.SmoothMarkerBouncing/pull/23

Error *"Uncaught TypeError: Cannot read property 'style' of undefined at makeMoveStep (leaflet.smoothmarkerbouncing.js:659)"* was due to the fact that method `bounce()` was called before `addTo(map)`.

Here is a working code snippet:

```javascript
    marker = L.marker(latlng, {icon: personIcon})
        .bindPopup(popupText)
        .setBouncingOptions({
            bounceSpeed: bounceSpeed,
        }).addTo(map).bounce();  // <- bounce called in the end
```

**Comment by neogeomat** [comment]
Hi, 

I am using [Leaflet routing machine](https://github.com/perliedman/leaflet-routing-machine) and the marker are created from that by dragging. If i bounce the marker then i get the style error. If i do `addTo(map)` to the marker and bounce it works but then i have two markers.

**Comment by hosuaby** [comment]
Hello @neogeomat . I don't have example with Leaflet routing machine. The key to solve your problem is to assure that marker was successfully added to the map before call to method `.bounce()`.

You you don't add marker by yourself, you need to find callback in the library that do it. It must be named something like: `onMarkerAdded()`.
